### ISSUE TITLE
Support PEP440 and "predicted release versioning" for "latest master"

### ISSUE THREAD

**Issue by ceball** [ioam/autover#12] opened 2018-01-23 11:07 UTC
Current python packaging tools and conda support PEP440.

Our projects already use a PEP440 release versioning scheme (e.g. `1.2.3`), and autover already supports that.

We'd also like to be able make packages between releases, but autover's version format there does 
not match PEP440. Based on discussion in #2, if git is `v0.2.0-5-g85da374`, then we'd like a package version of `0.2.1.dev5+g85da374`. Some projects will make packages available for every commit to master, in which case `0.2.1.dev5+g85da374` will be "the 5th developmental release of `0.2.1`" (see comments in #2 for more details).

See:
  * #11 where I have tried to add some tests for the version
  * #10 where I try to get the conda package version from autover (so that a project does not have to compose/specify the version format in more than one place): https://travis-ci.org/ioam/autover/jobs/332058395#L1716

**Comment by jlstevens** [comment] 2018-01-23 12:34
Thanks for working on those PRs. 

As far as I know, selecting the PEP440 format for non-release versions (and making sure it works) is the last thing we need to do before autover can be used as intended. Having tests is a great way to go about this.

**Comment by jlstevens** [comment] 2018-01-23 13:49
Just as a clarification, the release version format is already PEP440 as it is so simple - what we need to decide is the version format for other types of package e.g 'dev' versions or the 'nightlies' etc.

**Comment by ceball** [comment] 2018-01-23 13:50
Yeah, sorry, I just added a comment about that: https://github.com/ioam/autover/issues/8#issuecomment-359793727

**Comment by jlstevens** [comment] 2018-02-28 19:59
We found a PEP440 scheme we are happy with in #15. Other than adding the appropriate documentation about it it works. Closing.

**Closed as completed by jlstevens** 2018-02-28 19:59 UTC
